/**
 * pages/about.js
 *
 * Simple placeholder for an About page. For now it just renders some
 * Lorem Ipsum text, and exists so the app can demonstrate having an
 * informational page at the front of the list.
 */

/**
 * @param {HTMLElement} container
 * @param {Array} pages
 */
export function render(container, pages) {
  container.innerHTML = `
    <div class="p-4">
      <h1 class="mb-3">About</h1>
      <p>
      This is a page of widget-style apps with styling that I 
      generated by directing ChatGPT, Claude, and VSCode with Copilot.
      It's part of a larger-scope effort to update my online presence across multiple platforms.

      I leveraged AI as a middleman: I, the creator, bring the intent, and use the AI as an assistant towards the goal. I am using only free tools.
      </p>
      <p>
      I am trying to figure out how to make a career pivot into a middle-class tech-related role in The Land of Opportunity.
      I asked ChatGPT to create a branding guide based on that intent.
      The typeface that I wound up settling on is IBM Plex Sans. It is a sensible, highly-readable, modern typeface with a hint of the techy blockiness of mono type, without immediately making someone (including me) mistake it for Courier New.
      Also, it isn't as common as Roboto and Inter, giving my branding just a hint of personality.
      In the future, I may do something really daring and pick a second typeface for the titling. For now, I think I can get by with strictly-functional font size hierarchy.
      In addition, I used AI to generate a CSS file that conformed to the branding guide, complete with Bootstrap overrides. It was very long, so I know as much about it as you do.
      </p>
      <p>
      I first attempted to have VSCode build this in React due to its strengths across different hardware types, but because it has so many parts with specific functions, VSCode Copilot could not handle the task.
      At the suggestion of Claude, I generated a raw-Javascript single-page app,
      and added Bootstrap for components and responsive design capabilities.
      I also had it change the CSS file to target the new project structure.
      </p>
      <p>
      I made this project as a collection of low-scope, low-stakes widgets
      that anyone could use at random on a day-to-day basis. Because of the responsive design, they should work just as well on your phone for on-the-go as on you desktop.
      Maybe you could even run it in its own window and resize the width down, leaving it open next to a larger window as a companion.
      If you like any of this, feel free to bookmark this page and crack it open every now and then!
      </p>
      <p>
      More modestly, my coding abilities are not the best, and my online presence
      was overdue for an update, and this was a pretty efficient way of producing
      some useful front-end demos. This is the "make it exist part" that comes before "make it better".
      </p>
      <p>
      I wrote everything on this About page, not AI. I like you that much.
      </p>
    </div>`;
}
